version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipegrow
    container_name: pipegrow
    volumes:
      - .:/var/www
    ports:
      - "1443:443"
      - "180:80"
    networks:
      - pipegrow_network

networks:
  pipegrow_network:
